### ISSUE TITLE
Improve custom file checking mechanisms

### ISSUE THREAD

**Issue by RemyLau** [krishnanlab/PyGenePlexus#146]
## The problem
Custom file checking becomes more complicated as we add custom ``gsc`` on top of custom ``net_type``. Previously, the custom ``net_type`` is checked within its setter via a series of conditional checks.

https://github.com/krishnanlab/PyGenePlexus/blob/9b4f3c12e1095a92e6f505de052fed901681ecf5/geneplexus/geneplexus.py#L114-L140

Adding ``gsc`` customization requires rewriting the ``net_type`` checks to take into account the ``gsc``. However, ``net_type`` do not have access to the choice of ``gsc``. Furthermore, we will need to do the same for ``gsc`` checks.

## Solution

Check the standard and custom options of ``gsc`` and ``net_type`` separately.

* For standard (those come with ``PyGenePlexus``) options, check as before by comparing with the list of standard options.
* For custom, check availability in the data location when calling the respective setters.
* Finally, before exiting GenePlexus class init, call a final custom check function to validate the combination of ``gsc`` and ``net_type``.

## Working notes
* [x] Split ``gsc`` and ``net_type`` options into private attrs ``_xx_standard`` and ``_xx_custom``.
* Check custom files using ``_gsc_custom`` and ``_net_type_custom``
  * Files needed:
    * ``Edgelist_${net_type}.edg``
    * ``Data_${features}_${net_type}.npy``
    * ``Nodeorder_${net_type}.txt``
    * ``GSCOriginal_${gsc}.json``
    * ``GSC_${gsc}_${net_type}_GoodSets.json``
    * ``GSC_${gsc}_${net_type}_universe.json``
  * [x] Setter checks: ``gsc`` and ``net_type``
    * Split into ``_xx_stanard`` and ``_xx_custom``
    * Check ``_xx_custom``
      * ``NodeOrder_${net_type}.txt``
      * [ ] ``Edgelist_${net_type}.edg`` (make this optional? only needed for making subnet)
      * ``GSCOriginal_${gsc}.json``
  * [x] Custom files final checks
    * ``Data_${features}_${net_type}.npy``
    * ``GSC_${gsc}_${net_type}_GoodSets.json``
    * ``GSC_${gsc}_${net_type}_universe.json``
  * Note: only call auto download for standard options

**Comment by ChristopherMancuso** [comment]
Thanks for putting this detailed process together! It seems like this all makes sense to me.
