### ISSUE TITLE
change cv results for small genesets

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/PyGenePlexus#314]
right now -10 is displayed, but need to change to a message, possibly save real results as a string as well.

**Comment by vincerubinetti** [comment]
I think you're talking about having the `cross_validation` result field return either `[number, number, number]` or `string`?

For an API response, I think it's more conventional to return `None` (becomes `undefined` or `null` in the frontend javascript) if some field can't be computed or isn't relevant, and then just have docs explaining that something went wrong if that field is missing.

Either way, let me know what you change it to so I can update the frontend.

**Comment by ChristopherMancuso** [comment]
I was thinking it just always return a string in the end so something like "The auPRC values for each fold are 2.1, 3.4, 5.6" or "There were not enough genes to run CV". There really isn't anything wrong, so it isn't an error, it is a choice not to provide possibly unreliable metrics to the user.

**Comment by vincerubinetti** [comment]
I wouldn't recommend that. I'd have to parse the numbers out from that string, as would anyone wanting to use those numbers directly from the API. Also if you (or Arjun or anyone) wants to tweak the wording or capitalization of those sentences, that would require a package update. It's normally better just to return raw values, and document what they mean elsewhere. I think those strings are akin to comments, and the other fields we're returning, `df_convert_out`/`table_summary`/etc, don't have similar explanations in the response. Instead, we have `/functions/README.md` that fully documents every field of the response.

**Comment by ChristopherMancuso** [comment]
I see what you are saying, I'll try to figure out how to return something in the package when there is less than 15 genes to do CV

**Comment by ChristopherMancuso** [comment]
fixed with #325
