### ISSUE TITLE
change example and defaults

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/PyGenePlexus#53]
change the example and defaults to match PCD example on web server

**Comment by ChristopherMancuso** [comment]
I think the example could be for a BioGRID Embedding example as the user would have to download the data, so will no longer match the web server example. A good example is to use Bardet-Biedl_syndrome_1 with GSC set to DisGeNet

**Comment by ChristopherMancuso** [comment]
@RemyLau Two questions on this

1. I think it might be good to have a separate page on Read the Docs that walks through an example and displays some of the top predictions for at least the gene classification probabilities and both the GO and DisGeNet model similarity tables, and some of the biological insights are discussed. What are you thoughts on this?
2. If that seems like a good idea, would it make sense to have this gene set and output be the one used in the GitHub tests?

**Comment by RemyLau** [comment]
It is definitely nice to have, but at the same time, I feel like it's not necessary. If someone really needs that level of supervision, the webserver would much more intuitive to use. But I'm definitely not against it.

**Comment by ChristopherMancuso** [comment]
close and will open with a new issue for version 2
